language: generic
sudo: false

os:
- linux

services:
- docker

script:
- docker-compose run bintest
- mruby/build/x86_64-pc-linux-gnu/bin/ff -v

before_deploy:
- docker-compose run release
- export BUILD_VERSION=`rake local:version`
- sudo chmod -R 1777 releases
- ls -la releases
- ls -la releases/v$BUILD_VERSION

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
  - "releases/v$BUILD_VERSION/ff-$BUILD_VERSION-i386-apple-darwin14.tgz"
  - "releases/v$BUILD_VERSION/ff-$BUILD_VERSION-i686-pc-linux-gnu.tgz"
  - "releases/v$BUILD_VERSION/ff-$BUILD_VERSION-i686-w64-mingw32.tgz"
  - "releases/v$BUILD_VERSION/ff-$BUILD_VERSION-x86_64-apple-darwin14.tgz"
  - "releases/v$BUILD_VERSION/ff-$BUILD_VERSION-x86_64-pc-linux-gnu.tgz"
  - "releases/v$BUILD_VERSION/ff-$BUILD_VERSION-x86_64-w64-mingw32.tgz"
  skip_cleanup: true
  on:
    tags: true
    condition:
    - "$TRAVIS_OS_NAME == linux"
