compile: &defaults
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: rake compile
bintest:
  <<: *defaults
  command: rake test:bintest
clean:
  <<: *defaults
  command: rake clean
shell:
  <<: *defaults
  command: bash
release:
  <<: *defaults
  command: rake release
